# -*- coding: utf-8 -*-
"""Gene Expression Analytics Dashboard Using Human.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q85BAwWUHVsLG8ROnyiTc-muvW49xQjq
"""

!pip install streamlit
!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title('My Streamlit App')
# st.write('Hello from Colab!')
# 
# !streamlit run app.py

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("Human Protein Atlas Gene Expression Dashboard")

import pandas as pd

# Load TSV files
normal = pd.read_csv("normal_tissue.tsv", sep="\t")
cancer = pd.read_csv("cancer_cell_line.tsv", sep="\t")

# Add category labels
normal["Type"] = "Normal Tissue"
cancer["Type"] = "Cancer Cell Line"

import pandas as pd

# Load HPA data
df = pd.read_csv("normal_tissue.tsv", sep="\t")

# Show available columns
print(df.columns.tolist())

# Preview data
print(df.head())

normal.head()

cancer.head()

normal.columns

cancer.columns

hpa_data = pd.concat(
    [normal, cancer],
    ignore_index=True
)

hpa_data.head()

normal.shape, cancer.shape

normal.columns

cancer.columns

hpa_data = pd.concat( [normal, cancer], ignore_index=True)
hpa_data.head()

hpa_data.shape

hpa_data["Type"].value_counts()

hpa_data["Sample"] = hpa_data["Tissue"].fillna(
    hpa_data["Cell line"]
)

hpa_data[['Gene name','Sample','nTPM','Type']].head()

hpa_data["Type"].value_counts()

hpa_data.shape

hpa_data.head()

hpa_dashboard = hpa_data[
    ['Gene', 'Gene name', 'Sample', 'nTPM', 'Type']]

hpa_dashboard.isnull().sum()

hpa_dashboard['nTPM'] = pd.to_numeric(
    hpa_dashboard['nTPM'],
    errors='coerce'
)

hpa_dashboard.to_parquet(
    "HPA_expression.parquet")

hpa_dashboard.columns

hpa_dashboard.head()

hpa_dashboard.to_parquet("HPA_expression.parquet")

from google.colab import files

files.download("HPA_expression.parquet")